### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/mrp-addons#11]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] bom_lines_configurator
- [ ] mrp_bom_structure_show_child_with_manual_standard_cost
- [ ] mrp_bom_version_extension
- [ ] mrp_hook_extension
- [ ] mrp_inverse
- [ ] mrp_product_profit
- [ ] mrp_production_block_compute
- [ ] mrp_production_merge
- [ ] mrp_production_no_split_finished_product_move
- [ ] mrp_production_nogap_code
- [ ] mrp_production_sequential_lot
- [ ] mrp_production_traceability_sequential_lot
- [ ] mrp_routing_cost
- [ ] mrp_supplier_price
- [ ] mrp_unitary_production
- [ ] mrp_utilities
- [ ] product_attribute_value_related_operations
- [ ] quality_control_by_product
- [ ] quality_control_from_employee
- [ ] quality_control_from_event
- [ ] quality_control_from_hr_contract
- [ ] quality_control_from_partner
- [ ] quality_control_plan
- [ ] quality_control_ref_search
- [ ] quality_control_stock_inventory
- [ ] sale_mrp_link
- [ ] stock_valuation_extension
