### ISSUE TITLE
Migration to version 15.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/mrp-addons#166]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

# Modules to migrate

- [ ] mrp_bom_category
- [ ] mrp_bom_import
- [ ] mrp_bom_line_coef
- [ ] mrp_bom_line_note
- [ ] mrp_bom_reference
- [ ] mrp_cut
- [ ] mrp_manual_sale_info
- [ ] mrp_product_template_lineal
- [ ] mrp_product_version_to_bom
- [ ] mrp_routing_workcenter_capacity
- [ ] mrp_second_uom
- [ ] mrp_usability
- [ ] mrp_workorder_availability
- [ ] mrp_workorder_permission
- [ ] quality_control_claim
- [ ] quality_control_test_method
- [ ] quality_control_usability

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
