### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/mrp-addons#69]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] mrp_hook
- [ ] mrp_production_custom_variants_inherited_attributes
- [ ] mrp_production_erase
- [ ] mrp_production_generate_structure
- [ ] mrp_scheduled_products
- [ ] mrp_supplier_price
- [ ] mrp_usability
- [ ] mrp_workorder_grouping_by_material
- [ ] product_variant_custom
- [ ] product_variant_custom_dimensions
- [ ] product_variant_custom_dimensions_purchase
- [ ] product_variant_custom_purchase
- [ ] product_variant_custom_sale
- [ ] product_variant_custom_sale_mrp_link
- [ ] product_variant_custom_stock
- [ ] repair_full_editable
- [ ] sale_line_mrp_link
- [ ] sale_order_supplier_price

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
